### ISSUE TITLE
Issue: '@typescript-eslint/no-deprecated' seems broken

### ISSUE THREAD

**Issue by tools-aoeur** [tools-aoeur/eslint-config#13]
This proves to be very useful to catch migrations early, maybe at a warn instead of error level for the findings, but still we would get a proper notification of the deprecation. At the moment we have a project with MUI recently migrated to a new major release and want to see the problematic points other than looking into the code or locally setting up the tooling for that. We will probably forget to regularly check these points otherwise.

Is there any reason to not want this behavior by default (list up findings as warnings)?

**Comment by jdehaan** [comment]
The plugin is archived and not maintained anymore, alternatives?

**Comment by jdehaan** [comment]
Seems fixed now in https://github.com/typescript-eslint/typescript-eslint/pull/10374 which got integrated into [typescript-eslint@8.18.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.18.0)
